EXP_DIR: pvanet_full1_ohem_D_1500x2000
TRAIN:

  # BG_THRESH_LO: 0.0
  # we use gradient accumulation,
  # see solver.prototxt (iter_size: 2)
  # IMS_PER_BATCH: 1
  # adjust batch_size for iter_size
  BATCH_SIZE: 12000
  BATCH_OHEM_SIZE: 128
  USE_OHEM: True
  # Wasn't used in the paper (impact unknown).
  ASPECT_GROUPING: False

  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  SCALE_MULTIPLE_OF: 32
  MAX_SIZE: 2016
  SNAPSHOT_ITERS: 10000
  SCALES:
    - 1184
    - 1216
    - 1248
    - 1280
    - 1312
    - 1344
    - 1376
    - 1408
    - 1440

