EXP_DIR: pvanet_full1_ohem_upscale
TRAIN:

  # BG_THRESH_LO: 0.0
  # we use gradient accumulation,
  # see solver.prototxt (iter_size: 2)
  # IMS_PER_BATCH: 1
  # adjust batch_size for iter_size
  BATCH_SIZE: 2000
  BATCH_OHEM_SIZE: 128
  USE_OHEM: True
  # Wasn't used in the paper (impact unknown).
  ASPECT_GROUPING: False

  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  SCALE_MULTIPLE_OF: 32
  MAX_SIZE: 2016
  SNAPSHOT_ITERS: 10000
  SCALES:
    - 416
    - 448
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800
    - 832
    - 864
    - 896
    - 928
    - 960
    - 992
    - 1024
    - 1056
    - 1088
    - 1120
    - 1152
    - 1184
    - 1216
    - 1248
    - 1280
    - 1312
    - 1344
    - 1376
    - 1408
    - 1440
    - 1472
    - 1504
    - 1536
    - 1568
