EXP_DIR: pvanet_full1_ohem_D2
TRAIN:

  # BG_THRESH_LO: 0.0
  # we use gradient accumulation,
  # see solver.prototxt (iter_size: 2)
  # IMS_PER_BATCH: 1
  # adjust batch_size for iter_size
  BATCH_SIZE: 12000
  BATCH_OHEM_SIZE: 128
  USE_OHEM: True
  # Wasn't used in the paper (impact unknown).
  ASPECT_GROUPING: False

  HAS_RPN: True
  IMS_PER_BATCH: 1
  BBOX_NORMALIZE_TARGETS_PRECOMPUTED: True
  RPN_POSITIVE_OVERLAP: 0.7
  RPN_BATCHSIZE: 256
  PROPOSAL_METHOD: gt
  BG_THRESH_LO: 0.0
  SCALE_MULTIPLE_OF: 32
  MAX_SIZE: 1440
  SNAPSHOT_ITERS: 10000
  SCALES:
    - 416
    - 448
    - 480
    - 512
    - 544
    - 576
    - 608
    - 640
    - 672
    - 704
    - 736
    - 768
    - 800
    - 832
    - 864
